#!/usr/bin/env bash
# A Bash script that install nginx on unbuntu web01 server

# Update the packages manager
sudo apt-get update

# Install nginx
sudo apt-get -y install nginx

# Use ufw firewall to allow access to port 80 (http)
sudo ufw allow 'Nginx HTTP'

# Write 'Hello World!' in /var/www/html/index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test nginx configuration file
sudo nginx -t

# Start nginx server
sudo service nginx start
