#!/usr/bin/env bash
# A script that displays 'Best School' 10 times, but for
#+ the 9th iteration, displays 'Best School' and then 'Hi'
#+ on a newline.
num=1
while [ $num -le 10 ]
do
	if [ $num -eq 10 ]
	then
		 echo "Hi"
	else
		 echo "Best School"
	fi
	num=$((num + 1 ))
done
echo "Best School"
