#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59.
# while loop is used to impliment this.
hour=0
 echo "Hour: $hour"
while [ $hour -lt 12 ]
do
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		minute=$(( minute + 1 ))
	done
	hour=$(( hour + 1 ))
	echo "Hour: $hour"
done
