#!/usr/bin/env bash
# A Bash script that gives you information about the school file.
file = "school"
if [ -e "$file" ]
then
	echo "$file file exists"
else
	echo "$file file does not exist"
fi
if [ -e "$file" ]
then
	if [ -s "$file" ]
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi
	if [ -f "$file" ]
	then
		echo "$file is a regular file"
	fi
fi
	

	
