#!/usr/bin/env bash
# A script that creates an RSA key pair.
# Description:
# Name of the created private key is school.
# Number of bits in the created key is 4096.
# The created key is protected by the passphrase betty.

ssh-keygen -t rsa -b 4096 -P betty -f school
